### ISSUE TITLE
what should the input folder look like?

### ISSUE THREAD

**Issue by swharden** [swharden/SensaFluor#1]
## SensaFlow Operation
This issue relates to:
https://github.com/swharden/SensaFluor/blob/master/README.md#sensafluor-operation

## What image format will SensaFluor accept?

I propose 1 experiment = 1 video folder with individual TIFs:
* This video folder will contain individual TIFs (not a stack).
* This makes memory management much easier since not every computer can conveniently open a 50GB TIF stack. 
  * We could get around this programmatically (only reading byte positions in the file to memory as they're needed), but the code gets way simpler if we just start out opening single-channel single-slice TIFs
* ImageJ makes it easy to export as image sequence too.
* We can always add support for TIFF stacks later
* SensaFluor will create a `SensaFluor/` folder inside the input folder, and this is where it will dump its output CSV, PNG, HTML, and PDF files.
* Image order is defined by the filename (lexicographical order = chronological order)
  * this assumes every TIF is evenly spaced apart in time

***Is this format a good place to start? Do you have any alternative suggestions?***

**Comment by saglag** [comment]
TIF would be best, and most ubiquitous as every proprietary acquisition usually (I haven't encountered one that doesn't) has an export to TIF option.

For the ordering, it might be necessary to have a user input variable to define exposure time (would likely be in metadata) and frequency (might not be in metadata).

**Comment by swharden** [comment]
Thanks for the ideas!

I'll ensure the user can define _image acquisition rate (Hz)_ or its inverse _image acquisition period (sec)_

Exposure time and other TIF metadata probably isn't useful for the _analysis_, but since it's useful for the user to see it, I'll make it viewable in a text window.

For the early development, are you okay starting out to require a folder with thousands of TIFs instead of a single huge TIF stack file?

**Comment by saglag** [comment]
Absolutely. A folder of individual files prevents large stacks from being loaded all at once and either hogging or exceeding available memory.

**Comment by swharden** [comment]
* I placed these conclusions in [usage documentation](https://github.com/swharden/SensaFluor/tree/master/doc#input-format-specification)
* I also started [technical notes](https://github.com/swharden/SensaFluor/blob/master/dev/notes.md)
