### ISSUE TITLE
program icon

### ISSUE THREAD

**Issue by swharden** [swharden/SensaFluor#2]
Windows programs have a tiny icon in the upper left which also shows-up on the taskbar. What looks good? These are free to use (even commercially):
http://swharden.com/tmp/icons/VSIL2017.pdf

**Comment by swharden** [comment]
![image](https://user-images.githubusercontent.com/4165489/45246506-b6d22580-b2cf-11e8-8179-779c7a120b9e.png)

Yes, you could even get that icon in cornflower blue

**Comment by swharden** [comment]
I narrowed it down and will choose from http://swharden.com/tmp/icons/science/

**Comment by saglag** [comment]
I'm a fan of the color picker one or the mountain/sun in color. The B/W version may be more appropriate since the detectors used are more likely to be monochrome.

**Comment by swharden** [comment]
noted!
<img src="http://swharden.com/tmp/icons/science/Brightness_16x.svg" width="200">
http://swharden.com/tmp/icons/science/Brightness_16x.svg
